SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI, YYYY  FROM (
    SELECT YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION,
            IF( AVG(DEL_ELECT) OVER () + 2 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS am,
            IF( AVG(DEL_ELECT) OVER () + 3 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < DEL_ELECT,1,0) AS arred
        FROM sabana s 
        WHERE PIB > 9000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY YYYY, NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI, YYYY;


SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI, YYYY  FROM (
    SELECT YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION,
            IF( AVG(DEL_ELECT) OVER () + 2 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS am,
            IF( AVG(DEL_ELECT) OVER () + 3 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < DEL_ELECT,1,0) AS arred
        FROM sabana s 
        WHERE PIB BETWEEN 1000 AND 9000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY YYYY, NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI, YYYY;


SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI, YYYY  FROM (
    SELECT YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            YYYY, NOMBRE_DPT, NOMBRE_MPI, DEL_ELECT, RED, REGRESION,
            IF( AVG(DEL_ELECT) OVER () + 2 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS am,
            IF( AVG(DEL_ELECT) OVER () + 3 * STD(DEL_ELECT) OVER () < DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < DEL_ELECT,1,0) AS arred
        FROM sabana s 
        WHERE PIB < 1000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY YYYY, NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI, YYYY;