SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI  FROM (
    SELECT NOMBRE_DPT, NOMBRE_MPI, URIEL_DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            m.NOMBRE_DPT, m.NOMBRE_MPI,URIEL_DEL_ELECT, RED, REGRESION,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 2 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS am,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 3 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS arred
        FROM sabana s 
        JOIN municipios m ON (s.DPTO, s.MPIO) = (m.DPTO, m.MPIO)
        WHERE PIB > 9000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI;

SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI  FROM (
    SELECT NOMBRE_DPT, NOMBRE_MPI, URIEL_DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            m.NOMBRE_DPT, m.NOMBRE_MPI,URIEL_DEL_ELECT, RED, REGRESION,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 2 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS am,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 3 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS arred
        FROM sabana s 
        JOIN municipios m ON (s.DPTO, s.MPIO) = (m.DPTO, m.MPIO)
        WHERE PIB BETWEEN 1000 AND 9000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI;


SELECT MAX(GRAVEDAD) AS GRAVEDAD, NOMBRE_DPT, NOMBRE_MPI  FROM (
    SELECT NOMBRE_DPT, NOMBRE_MPI, URIEL_DEL_ELECT, RED, REGRESION, am+ar+amreg+arreg+amred+arred AS GRAVEDAD FROM (
        SELECT 
            m.NOMBRE_DPT, m.NOMBRE_MPI,URIEL_DEL_ELECT, RED, REGRESION,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 2 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS am,
            IF( AVG(URIEL_DEL_ELECT) OVER () + 3 * STD(URIEL_DEL_ELECT) OVER () < URIEL_DEL_ELECT,1,0) AS ar,
            IF( AVG(REGRESION) OVER () + 2 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS amreg,
            IF( AVG(REGRESION) OVER () + 3 * STD(REGRESION) OVER () < URIEL_DEL_ELECT,1,0) AS arreg,
            IF( AVG(RED) OVER () + 2 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS amred,
            IF( AVG(RED) OVER () + 3 * STD(RED) OVER () < URIEL_DEL_ELECT,1,0) AS arred
        FROM sabana s 
        JOIN municipios m ON (s.DPTO, s.MPIO) = (m.DPTO, m.MPIO)
        WHERE PIB BETWEEN 0 AND 1000
    ) T 
    WHERE am+ar+amreg+arreg+amred+arred > 0
) M
GROUP BY NOMBRE_DPT, NOMBRE_MPI
ORDER BY GRAVEDAD DESC, NOMBRE_DPT, NOMBRE_MPI;