SELECT
  PIB,
  PARTICIPACIONES,
  REGALIAS,
  URIEL_CENSO_ELECT,
  URIEL_CENSO_HAB,
  HOMICIDIOSx100K_HAB,
  URIEL_DEL_ELECT
FROM
  `unir-tfm-007.inicial.TFM_DB`
WHERE
  (
    PIB IS NOT NULL
    OR PARTICIPACIONES IS NOT NULL
    OR REGALIAS IS NOT NULL
    OR URIEL_DEL_ELECT IS NOT NULL
  )